name: Hacer una sugerencia
description: "¿Se te ocurren formas de mejorar la app? ¡Estoy encantado de oírlas!"
title: "[SUGERENCIA]: "
labels: ["sugerencia"]
assignees:
  - ZakaHaceCosas
body:
  - type: textarea
    id: suggestion-details
    attributes:
      label: Detalles de la sugerencia
      description: Explica en detalle tu sugerencia para mejorar la app
      placeholder: Escribe aquí tu sugerencia
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Beneficios de la sugerencia
      description: Describe cómo esta sugerencia mejorará la app
      placeholder: Con tus propias palabras, ¿por qué tu idea es una gran idea?
    validations:
      required: true
  - type: textarea
    id: implementation-ideas
    attributes:
      label: Ideas para la implementación (opcional)
      description: ¿Se te ocurre alguna idea de como podríamos implementar esta sugerencia?
      placeholder: Escribe aquí tus ideas. ¿De qué manera podemos añadir tu idea a la app?
    validations:
      required: false

